In [3]:
#Exercise 1: Create and reshape numpy array
import numpy as np

# Create array from 1 to 10 and reshape to 2x5
arr = np.arange(1, 11).reshape(2, 5)
print("Exercise 1:\n", arr)

Exercise 1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
#Exercise 2: Extract elements from numpy array
# Create array from 1 to 20 and extract elements between 5th and 15th index
arr = np.arange(1, 21)
extracted = arr[5:15]  # Note: Python uses 0-based indexing and end index is exclusive
print("\nExercise 2:\n", extracted)


Exercise 2:
 [ 6  7  8  9 10 11 12 13 14 15]


In [5]:
#Exercise 3: Create and modify Pandas Series
import pandas as pd

# Create Series and add new item
series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
series['pears'] = 4
print("\nExercise 3:\n", series)



Exercise 3:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [ ]:
#Exercise 4: Create DataFrame
