In [3]:
#Exercise 1: Create and reshape numpy array
import numpy as np

# Create array from 1 to 10 and reshape to 2x5
arr = np.arange(1, 11).reshape(2, 5)
print("Exercise 1:\n", arr)

Exercise 1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
#Exercise 2: Extract elements from numpy array
# Create array from 1 to 20 and extract elements between 5th and 15th index
arr = np.arange(1, 21)
extracted = arr[5:15]  # Note: Python uses 0-based indexing and end index is exclusive
print("\nExercise 2:\n", extracted)


Exercise 2:
 [ 6  7  8  9 10 11 12 13 14 15]


In [5]:
#Exercise 3: Create and modify Pandas Series
import pandas as pd

# Create Series and add new item
series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
series['pears'] = 4
print("\nExercise 3:\n", series)



Exercise 3:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [6]:
#Exercise 4: Create DataFrame
# Create DataFrame with 10 rows
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'],
    'age': [25, 32, 28, 35, 29, 42, 31, 27, 38, 45],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'M', 'F', 'M']
}
df = pd.DataFrame(data)
print("\nExercise 4:\n", df)


Exercise 4:
       name  age gender
0    Alice   25      F
1      Bob   32      M
2  Charlie   28      M
3    David   35      M
4      Eve   29      F
5    Frank   42      M
6    Grace   31      F
7    Henry   27      M
8      Ivy   38      F
9     Jack   45      M


In [7]:
# Add occupation column with repeating values
occupations = ['Programmer', 'Manager', 'Analyst'] * 3 + ['Programmer']  # To make 10 items
df['occupation'] = occupations[:10]  # Ensure we only take 10 items
print("\nExercise 5:\n", df)


Exercise 5:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   28      M     Analyst
3    David   35      M  Programmer
4      Eve   29      F     Manager
5    Frank   42      M     Analyst
6    Grace   31      F  Programmer
7    Henry   27      M     Manager
8      Ivy   38      F     Analyst
9     Jack   45      M  Programmer


In [8]:
# Select rows where age >= 30
filtered_df = df[df['age'] >= 30]
print("\nExercise 6:\n", filtered_df)


Exercise 6:
     name  age gender  occupation
1    Bob   32      M     Manager
3  David   35      M  Programmer
5  Frank   42      M     Analyst
6  Grace   31      F  Programmer
8    Ivy   38      F     Analyst
9   Jack   45      M  Programmer


In [9]:
# Save to CSV and read back
df.to_csv('people_data.csv', index=False)
read_df = pd.read_csv('people_data.csv')
print("\nExercise 7:\n", read_df)


Exercise 7:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   28      M     Analyst
3    David   35      M  Programmer
4      Eve   29      F     Manager
5    Frank   42      M     Analyst
6    Grace   31      F  Programmer
7    Henry   27      M     Manager
8      Ivy   38      F     Analyst
9     Jack   45      M  Programmer
